on:
  push:

env:
  PARALLEL_KEY: parallel

jobs:
  AA:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10

  AB:
    runs-on: ubuntu-latest
    needs:
      - AA
    strategy:
      matrix:
        tag:
          - FIRST
          - SECOND
    concurrency:
      group: "${{ matrix.tag }}"
      cancel-in-progress: false
    steps:
      - run: sleep 60
      - run: echo AB

  BA:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5

  BB:
    runs-on: ubuntu-latest
    needs:
      - BA
    strategy:
      matrix:
        tag:
          - SECOND
          - THIRD
    concurrency:
      group: "${{ matrix.tag }}"
      cancel-in-progress: false
    steps:
      - run: sleep 60
      - run: echo BB

  CA:
    runs-on: ubuntu-latest
    needs:
      - AB
      - BB
    steps:
      - run: echo CA

